live_config_reload = true
import = ["/Users/Edge/workspace/config/alacritty/dracula.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "MesloLGS NF"
style = "Regular"

[font.bold_italic]
family = "MesloLGS NF"
style = "BoldItalic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.offset]
x = 0
y = 6

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true

[window.padding]
x = 8
y = 8
