live_config_reload = true
# import = ["/Users/Edge/workspace/config/alacritty/dracula.toml"]
import = ["/Users/Edge/workspace/config/alacritty/catppucin-mocha.toml"]
# import = ["/Users/Edge/workspace/config/alacritty/catppucin-macchiato.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "MesloLGS NF"
style = "Regular"

[font.bold_italic]
family = "MesloLGS NF"
style = "BoldItalic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.offset]
x = 0
y = 5

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Buttonless"
dynamic_title = true
dynamic_padding = true

[window.padding]
x = 1
y = 0

